name: chemprop_egsar

channels:
  - conda-forge
  - pytorch
  - rdkit
  
dependencies:
  - python==3.8.6
  - flask>=1.1.2
  - gunicorn>=20.0.4
  - hyperopt>=0.2.3
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pandas-flavor>=0.2.0
  - pip>=20.0.2
  - scikit-learn>=0.22.2.post1
  - scipy>=1.4.1
  - tensorboardX>=2.0
  - tqdm>=4.45.0
  - pytorch==1.5.1
  - torchvision==0.6.1
  - cudatoolkit=10.1
  - rdkit
  - pip:
    - typed-argument-parser>=1.6.1
    - chemprop>=1.0.0
    - POT

